### PR TITLE
Fix audio, show audio player in chat window 

### PR DESCRIPTION
**Pull request by hsaadawy**

### CODE REVIEW

**Comment by CodeBast4rd** [comment]
The window width and content lenght should be replaced by a injectable constant provider.
ImageLink to MediaLink.
Remove debugger statement.

**Comment by hsaadawy** [comment]
@CodeBast4rd thanks for your replying, and we have many feature will be implemented ASAP like forward message and reply on message, so we need theses features in your npm packages is that possible ?

**Comment by hsaadawy** [comment]
@CodeBast4rd thanks again it's awesome, could you please hint me with sample code to handle this new architecture ,off course if you have a time :)

**Comment by hsaadawy** [comment]
@CodeBast4rd  as we use @pazznetwork/ngx-cha npm package in our angular project,thanks

**Comment by CodeBast4rd** [comment]
See for example the component: ChatMessageInComponent.

`
<ngx-chat-bubble>
    <ngx-chat-bubble-avatar [avatar]="contact.avatar"
                            [avatarClickable]="true"
                            [contact]="contact"
                            [showAvatar]="showAvatar">
    </ngx-chat-bubble-avatar>
    <ngx-chat-message-text-area [textContent]="message.body">
    </ngx-chat-message-text-area>
    <ngx-chat-message-image [textContent]="message.body">
    </ngx-chat-message-image>
    <ngx-chat-bubble-footer [formattedDate]="message.datetime | date:chatService.translations.timeFormat"
                            [nick]="contact.name">
    </ngx-chat-bubble-footer>
</ngx-chat-bubble>
`

You can add the forwarding/reply in the ngx-chat-bubble-footer  or write a  `<ngx-chat-bubble-footer-extended ngProjectAs="ngx-chat-bubble-footer" ...>` .

If you want to write the code in your own project you can always just write a new ChatWindowComponent and replace the default ChatBarWindows.

**Comment by hsaadawy** [comment]
@CodeBast4rd  awesome!!, so how can install npm package,like a normal way **npm install --save @pazznetwork/ngx-chat strophe.js@1.4.4 rxjs@7.5.7**  or there is a new command, thanks for a great support :)

**Comment by CodeBast4rd** [comment]
`npm install --save @pazznetwork/ngx-chat @pazznetwork/strophets rxjs@7.5.7`

But only after the https://github.com/pazznetwork/ngx-chat/tree/alternative-xmpp-adapter branch is merged and a new npm package deployed.

Now you could use it as a git dependency but its still full of errors.

But writing an own ChatWindowComponent and ChatBarWindows is also possible in the current public version.

**Comment by hsaadawy** [comment]
"But writing an own ChatWindowComponent and ChatBarWindows is also possible in the current public version."
How could we do this, if there is a reference or tutorial to do, sample code as a hint please :)

**Comment by hsaadawy** [comment]
@CodeBast4rd  we take care of your comments ,and standby for any comments,thanks

**Comment by hsaadawy** [comment]
@CodeBast4rd Hello sir , i hope you well and safe, could you please accept this pull request!, thanks

**Comment by CodeBast4rd** [comment]
No all review comments were resolved.

**Comment by hsaadawy** [comment]
@CodeBast4rd  we were covered all comments and commit them 
https://github.com/pazznetwork/ngx-chat/pull/128/commits/91a55b509e9f37650cbe6e27b04d5d5db46cccff

**Comment by CodeBast4rd** [comment]
the window width style was not made configureable. But I will refactor this myself. I should be able to merge the PR in 45 min.

**Comment by hsaadawy** [comment]
@CodeBast4rd  awesome, we really appreciated your effort, we install **@pazznetwork/ngx-chat": "^0.14.4"** in our project, so when can we update npm package in our project to get show the audio player in chat window.

**Comment by CodeBast4rd** [comment]
@hsaadawy https://github.com/hsaadawy/ngx-chat/pull/1

**Comment by hsaadawy** [comment]
@CodeBast4rd  merged !, please notify me when new build is ready thanks

**Comment by CodeBast4rd** [comment]
New version is published and available

**Comment by hsaadawy** [comment]
@CodeBast4rd  Hello sir, after trying to upgrade angular version to v14 as we use v12 , we have a bunch of errors that may will take a while to be solved, so please advice to get the new changes in package not depends on angular 14 , thanks

**Comment by hsaadawy** [comment]
@CodeBast4rd  No matching version found for @angular/cdk@14.2.6.

WhatsApp Image 2022-10-18 at 10 04 31 PM

**Comment by CodeBast4rd** [comment]
It is a peer dependency it means your project needs to have a angular/cdk at runtime.

**Comment by hsaadawy** [comment]
Please advise @CodeBast4rd 
Screenshot_20221019-090520

**Comment by CodeBast4rd** [comment]
0.14.10 published now with downgrade to 14.2.5. In the future a quickfix is to use https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by hsaadawy** [comment]
Hello @CodeBast4rd we are appreciated your big support , now we are facing this error "npm WARN peer @xmpp/client@"^0.9.0" from @pazznetwork/ngx-chat@0.14.10"
after downgrade "@xmpp/client" getting the punch of errors ,please advise thanks again
ab4b2867-f474-415e-84b5-9dbd824495cc

**Comment by CodeBast4rd** [comment]
`{
  "name": "ngx-chat-demo",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "dependencies": {
    "@angular/animations": "14.2.7",
    "@angular/cdk": "14.2.5",
    "@angular/common": "14.2.7",
    "@angular/compiler": "14.2.7",
    "@angular/core": "14.2.7",
    "@angular/forms": "14.2.7",
    "@angular/platform-browser": "14.2.7",
    "@angular/platform-browser-dynamic": "14.2.7",
    "@angular/router": "14.2.7",
    "@types/ltx": "^3.0.2",
    "@xmpp/client": "^0.13.1",
    "@pazznetwork/ngx-chat": "0.14.12",
    "rxjs": "~7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {}
}
`

Fixed, Reduced, Tested.

**Comment by hsaadawy** [comment]
@CodeBast4rd , we get these
IMG-20221020-WA0003

**Comment by CodeBast4rd** [comment]
0.14.13 should have fixed them

**Comment by hsaadawy** [comment]
@CodeBast4rd  we get this
IMG-20221021-WA0004

**Comment by hsaadawy** [comment]
@CodeBast4rd ,hello sir could you please support us to solve the previous error, thanks 🙏

**Comment by CodeBast4rd** [comment]
A fast fix would be to create an own ChatStyle file with the same interface. I will fix it tomorrow morning.

**Comment by CodeBast4rd** [comment]
Fixed with 0.14.14

**Comment by hsaadawy** [comment]
@CodeBast4rd thanks great job,is there any documentation for this package or hint to handle forward, reply and star message,also need enable notifications sound

**Comment by CodeBast4rd** [comment]
Functions depending on a server logic are all implemented following the XMPP Protocol see https://xmpp.org/. Every other implementation follows the best practices for Angular.  Interchangeable components and services for each specific tasks.

For Notification Sounds you would need a new service with an interface with the least amount of necessary data  and a method to check if there is a notification sound for a user.

To store data you can use an own backend or you can use the https://xmpp.org/extensions/xep-0060.html orienting yourself by the read messages plugin implementation.

**Comment by hsaadawy** [comment]
@CodeBast4rd very helpful, i asked you before if we can use the our changes on any version compatible with angular 12 we used before ngx version 0.14.4,as we will have an intensive changes and fully testing after upgrading

**Comment by CodeBast4rd** [comment]
You can checkout the tag v0.12.0 create a branch from it. Cherry pick the changes you want. Follow the readme and test the package and ask me to release from your branch or you can use your github repository as a package source for your npm or you can publish the package yourself.

**Comment by hsaadawy** [comment]
@CodeBast4rd Hello sir, I hope you well and safe, i follow your steps to merge to tag v0.12.0 and create chery pick for our commit but i cant create pull request ,please advice.
thanks
image

**Comment by CodeBast4rd** [comment]
> You can checkout the tag v0.12.0 create a branch from it. 
git checkout 
```
cd ngx-chat # switch into the pazznetwork/ngx-chat repo
git checkout v0.12.0
git branch -d angular-12 # in case you have the old branch locally
git switch -c angular-12
git cherry-pick 990475ce805acaa8d5d403ed5850ed7f32910d95
git cherry-pick 9623bf43f6a6989d23794ed20d88b5a05fc69997
git cherry-pick 91a55b509e9f37650cbe6e27b04d5d5db46cccff
git cherry-pick e82426e1357b0690f359f305be5d779ab12c3e7c
git cherry-pick 0ccb0636388cf86ed25b7fae4a1ec9fc68b22a08
git push --set-upstream origin angular-12
```

Notify me when the branch is online.

**Comment by hsaadawy** [comment]
@CodeBast4rd  i follow your steps and get this error
You don't have permissions to push to 'pazznetwork/ngx-chat' on GitHub. Would you like to create a fork and push to it instead?

**Comment by hsaadawy** [comment]
@CodeBast4rd  the branch
https://github.com/hsaadawy/ngx-chat/tree/angular-12

**Comment by hsaadawy** [comment]
@CodeBast4rd  i get these errors
```
 json package 

"dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/cdk": "^14.0.6",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@pazznetwork/ngx-chat": "^0.12.2",
    "@xmpp/client": "^0.9.2",
    "ltx": "^3.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
```
Screenshot 2022-11-17 165545

**Comment by hsaadawy** [comment]
@CodeBast4rd  please any help or hint there,thanks

**Pull request merged**
